# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_stream', '0003_auto_20170216_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_parent',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
