# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 17:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_stream', '0005_auto_20170216_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
