# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_stream', '0006_auto_20170216_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_created',
            field=models.DateTimeField(),
        ),
    ]
