# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_stream', '0007_auto_20170216_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_filter',
            field=models.BooleanField(default=True),
        ),
    ]
