# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_stream', '0008_account_account_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_filter',
            new_name='filter_by_hashtags',
        ),
    ]
