# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 17:05
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_stream', '0014_auto_20170309_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_pin',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('testgroup', 'testgroup'), ('Aberdeen_University', 'Aberdeen_University'), ('Aberdeen_HSRU', 'Aberdeen_HSRU'), ('Aberdeen_COPS', 'Aberdeen_COPS'), ('Aberdeen_CLSM', 'Aberdeen_CLSM'), ('Aberdeen_CASS', 'Aberdeen_CASS'), ('groupgroup', 'groupgroup')], max_length=100, null=True), blank=True, null=True, size=8),
        ),
    ]
