# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_stream', '0014_auto_20170309_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_group',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
