# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_stream', '0017_auto_20170316_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter_stream.group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter_stream.group'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter_stream.group'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_pin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter_stream.group'),
        ),
    ]
