# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_stream', '0019_auto_20170317_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter_stream.group'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_pin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
