# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_stream', '0020_auto_20170317_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_handle',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_html',
            field=models.CharField(editable=False, max_length=5000),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_text',
            field=models.CharField(editable=False, max_length=145),
        ),
    ]
