# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-06 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_stream', '0022_auto_20170323_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='hashtag_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag_hash',
            field=models.CharField(max_length=100),
        ),
    ]
